version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    volumes:
      - etcd-data:/etcd-data
    ports:
      - "2379:2379" # Porta cliente padrão
      - "2380:2380" # Porta peer
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster=node1=http://etcd:2380
      - --initial-cluster-state=new
    environment:
      ETCD_NAME: node1
    networks:
      - backend

  postgres_databases:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 172983456
      POSTGRES_USER: root
      POSTGRES_DB: eventostec
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./zrpc/01.sql:/docker-entrypoint-initdb.d/01.sql
      - ./zrpc/02.sql:/docker-entrypoint-initdb.d/02.sql
      - ./zrpc/03.sql:/docker-entrypoint-initdb.d/03.sql
    networks:
      - backend

  zrpc:
    build:
      context: .
      dockerfile: ./zrpc/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_databases
      - redis
      - etcd
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
  redis-data:
  etcd-data:
