// Code generated by goctl. DO NOT EDIT.
// Source: zrpc.proto

package server

import (
	"context"

	"eventos-tec/common/pb"
	"eventos-tec/zrpc/internal/logic"
	"eventos-tec/zrpc/internal/svc"
)

type ZrpcServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedZrpcServiceServer
}

func NewZrpcServiceServer(svcCtx *svc.ServiceContext) *ZrpcServiceServer {
	return &ZrpcServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ZrpcServiceServer) ListEvents(ctx context.Context, in *__.ListEventsRequest) (*__.ListEventsResponse, error) {
	l := logic.NewListEventsLogic(ctx, s.svcCtx)
	return l.ListEvents(in)
}

// rpc EventDetails(EventDetailsRequest) returns (EventDetailsResponse);
func (s *ZrpcServiceServer) CreateEvent(ctx context.Context, in *__.CreateEventRequest) (*__.CreateEventResponse, error) {
	l := logic.NewCreateEventLogic(ctx, s.svcCtx)
	return l.CreateEvent(in)
}

func (s *ZrpcServiceServer) CreateCoupon(ctx context.Context, in *__.CreateCouponRequest) (*__.CreateCouponResponse, error) {
	l := logic.NewCreateCouponLogic(ctx, s.svcCtx)
	return l.CreateCoupon(in)
}
